---
title: "Graded Homework 2 for 5703 (Solutions)"
output: html_document
---

```{r setup, include=FALSE}
 # keep this chunk in your .Rmd file
 knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

## Exercise 1

### Problem 1





### Problem 3

```{r}
library(markovchain)
library(lubridate)
library(dplyr)
```

```{r}
data = c("H", "H", "S", "S", "H", "S", "S", "H")
markovchainFit(data, method = "mle", byrow = T)
```
```{r}
year(mdy("11/30/96")) %% 100
```

```{r}

parse_date <- function(x, start_year=1911) {
  x <- mdy(x)
  y <- year(x) %% 100
  year(x) <- ifelse(y > start_year %% 100, 1900+y, 2000+y)
  x
}


centralPark <- read.csv("./CentralPark.csv")
snow <- centralPark[1:36524, ] %>% 
  mutate(DATE_OBJ=parse_date(DATE)) %>% 
  arrange(DATE_OBJ) %>% 
  filter(!is.na(SNWD) & DATE_OBJ < mdy("11/30/1995") & DATE_OBJ > mdy("1/1/1912")) %>% 
  mutate(SNOW_DAY=factor(ifelse(SNWD > 50, "SnowDay", "NoSnow"))) %>% 
  mutate(YEAR=year(DATE_OBJ)) %>% 
  mutate(Christmas=(month(DATE_OBJ) == 12 & 
                      day(DATE_OBJ) >=17 & day(DATE_OBJ) <= 31)) %>% 
  filter(Christmas == TRUE) %>% 
  group_by(YEAR) %>% 
  summarise(Weather=paste(SNOW_DAY, collapse = ",")) 
  
realizations <-stringr::str_split(snow$Weather, pattern = ",") 
mcFit <- markovchainFit(realizations, "mle")
#select(DATE, snowDay)
```

```{r}
markovchainFit(c("1", "0", "0", "1"), "mle")$estimate
```
```{r}
markovchainFit(c("0", "1", "1", "1"), "mle")$estimate
```
```{r}
markovchainFit(list(c("1", "0", "0", "1"), 
c("0", "1", "1", "1")), "mle")$estimate
```

```{r}
library(SMPracticals)
data(intron)
fit <- MClik(intron)
```
```{r}
seq2matHigh(data, order = 3)
```

